### ISSUE TITLE
Make the game work with no player

### ISSUE THREAD

**Issue by xordspar0** [synthein/synthein#210]
If your starting scene doesn't have a player in it, currently the game crashes. This should be allowed so that it's easier to make scenes for testing missiles and other new weapons. Part of this will involve picking a place for that player's camera to start even with no structure to pin it to.

**Comment by randomguyeatspotato** [comment]
I don't like the way this is referred to. I think that a player is what interacts with the game. So if anything is drawn to the screen it should require a player. I would agree that setting it up so that the player does not need a ship would be a good idea.
