### ISSUE TITLE
Circle menus need to support labels

### ISSUE THREAD

**Issue by randomguyeatspotato** [synthein/synthein#65]
This is currently only usable for the AIs.

**Comment by xordspar0** [comment]
Do you have any ideas about what you would like this to look like? Could you try to describe or sketch any ideas you have?

**Comment by randomguyeatspotato** [comment]
The main thing is that you can see what each option is. I was just thinking black text with the menu color as the back ground. I need to do the clean up first and I just figured out how I want to do it.
